name: scontreeno
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^3.1.0+1
  fl_chart: ^0.4.1
  flutter_nfc_reader: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
   - res/images/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: res/fonts/google_sans/GoogleSans-Regular.ttf
        - asset: res/fonts/google_sans/GoogleSans-Italic.ttf
          style: italic
        - asset: res/fonts/google_sans/GoogleSans-Medium.ttf
          weight: 500
        - asset: res/fonts/google_sans/GoogleSans-Bold.ttf
          weight: 700
